# Enable logs for pin matrix debugging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_ZMK_LOG_LEVEL=3

# delay log thread start a bit for attaching a terminal
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

# fix deprecated symbol
CONFIG_NRF_STORE_REBOOT_TYPE_GPREGRET=n